config/routes.rb
Rails.application.routes.draw do
  namespace :administrators do
    resources :users, only: [:index, :edit, :update, :show, :destroy, :create] do
      resources :addresses, only: [:index, :new, :create, :edit, :update, :destroy]
    end
    resources :products do
      resources :discs, only: [:create, :update]
      resources :songs, only: [:create, :update]
    end
    resources :labels, only: [:new, :create, :update]
    resources :genres, only: [:new, :create, :update]
    resources :artists, only: [:new, :create, :update]
    resources :arrivals, only: [:index, :show, :new, :create]
  end
  get 'administrators/top' => 'administrators#top', as: "administrators_top"
  # resources :administrators
  # get 'administrators' => 'administrators#top', as: 'administrators'
  # get 'administrators/users/:id' => 'administrators#show', as: 'administrators_user_main'
  # get 'administrators/users/:id/edit' => 'administrators#edit', as: 'edit_administrators_user_main'
  # patch 'administrators/users/:id' => 'administrators#update', as: 'update_administrators_user_main'
  # put 'administrators/users/:id' => 'administrators#update'
  # get 'administrators/show'
  # get 'administrators/edit'
  root 'products#index'

  devise_for :administrators, controllers: {
    sessions:      'administrators/sessions',
    passwords:     'administrators/passwords',
    registrations: 'administrators/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  get 'thanks/index' => 'thanks#index', as: "thanks"

  resources :users, only: [:index, :edit, :update, :show, :destroy, :create] do
    resources :addresses, only: [:index, :new, :create, :edit, :update, :destroy, :show]
  end

resources :products do
      resources :discs, only: [:create, :update]
      resources :songs, only: [:create, :update]
    end

  resources :receipts, only: [:new, :create, :update]




  get "search" => "products#search"

  resources :cart_items, only: [:create, :update]


#開発の便宜上、一旦ネストを外す　ここから


  resources :arrivals, only: [:index, :show, :new, :create]



#開発の便宜上、一旦ネストを外す　ここまで
  resources :labels, only: [:new, :create, :update]
  resources :genres, only: [:new, :create, :update]
  resources :artists, only: [:new, :create, :update]



  resources :carts, only: [:index, :create, :destroy]
  put "cart_update" => "carts#update"
  # 引数を指定せずにupdateアクションを呼び出すため、別でルーティングを設定

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :cart_items
	has_many :products, through: :cart_items
	belongs_to :user
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def index
		@cart_items = current_user.cart.cart_items.all
		sum = 0
		@cart_items.each do |item|
			item_amount = item.product_amount
			sum += item.product.price*item_amount
		end
		@total_price = sum
	end

	def create
		if user_signed_in?
			cart_item = current_user.cart.cart_items.find_or_initialize_by(product_id: params[:cart_item][:product_id])
			# .find_or_initialize_byは、対象から()の条件を満たすレコードを探してくる。見つからなければレコードを作る直前で止まる。
			if cart_item.new_record?#initializeされた場合
				cart_item.product_amount = params[:cart_item][:product_amount].to_i
			elsif cart_item.product_amount.to_i + params[:cart_item][:product_amount].to_i > cart_item.product.stock_amount.to_i
				#findされて、すでにカート内に入っていた数量とカートに入れようとしている数量の合計が、商品の在庫数を超える場合
				flash[:amount_over] = "商品の在庫数を超えてカートに追加することはできません。"
			else
				cart_item.product_amount += params[:cart_item][:product_amount].to_i
			end
			cart_item.save!
			redirect_to carts_path
		else
			redirect_to new_user_session_path
		end
	end

	def update
		update_params.each do |id, product_amount|
		cart_item = CartItem.find(id)
		cart_item.update(product_amount)
		end
		redirect_to carts_path
	end

	def destroy
		cart_item = CartItem.find(params[:id])
	    cart_item.destroy
	    redirect_to carts_path
	end

	private

	def update_params
		params.permit(cart_items: [:product_amount])[:cart_items]
	end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/index.html.erb
<h2>ショッピングカート</h2>




<% if flash[:amount_over] %>
	<p><%= flash[:amount_over] %></p>
<% end %>


<% if @cart_items.blank? %>
<div class="cart-blank">
	<h3>カート内に商品がありません。</h3>
	<%= link_to "商品一覧に戻る", products_path,:class=>"button" %>
</div>

<% else %>
	<!-- each文をform_tagで囲って数量の一括更新を実装 -->
	<%= form_tag cart_update_path, method: :put do %>
		<!-- 引数を渡さずにupdateアクションを呼び出すため、別でルーティングを設定 -->

	<div class="cart clearfix">
		<div class="cart-left clearfix">
				<% @cart_items.each do |cart_item|%>
					<div class="cart-item">
						<div>
							<%= link_to product_path(cart_item.product_id) do %>
							<!-- 商品画像 -->
								<%= attachment_image_tag cart_item.product, :product_image, fallback: "no_image.jpg", size: "150x150",class: "cart-item-logo" %>
							<% end %>
						</div>

						<div class="cart-item-string">
								<!-- 商品名 -->
								<p class="cart-product-name"><%= link_to cart_item.product.product_name, product_path(cart_item.product_id) %></p>
								<!-- 税込価格 -->
								<p><%= (cart_item.product.price*1.1).floor %>円（税込み）</p>
								<!-- 購入数編集 -->
							    <%= fields_for "cart_items[]", cart_item do |fi| %>
									<%= fi.select :product_amount, 1..cart_item.product.stock_amount %>枚
									<!-- プルダウンには１〜在庫数までを表示 -->
						    	<% end %>
						    	<!-- 削除 -->
								<%= link_to "削除", cart_path(cart_item.id), method: :delete, data:{ confirm: '本当に消しますか？' },:class=>"cart-destroy-button" %>
						</div>
					</div>
				<% end %>
					<!-- 数量を更新 -->
					<%= submit_tag "数量を更新",:class=>"cart-update-button" %></p>

			<% end %>
		</div>

		<div class="cart-right">
			<p>合計金額：</p>
			<p class="purchase-price"><%= (@total_price*1.1).floor  %>円</p>
			<p>送料：　500円（一律）</p>
			<p><%= link_to "購入確認へ進む", new_receipt_path,:class=>"button" %></p>
			<p><%= link_to "もっと買い物をする", products_path,:class=>"link" %></p>
		</div>
	</div>
<% end %>