config/routes.rb
Rails.application.routes.draw do
  namespace :administrators do
    resources :users, only: [:index, :edit, :update, :show, :destroy, :create] do
      resources :addresses, only: [:index, :new, :create, :edit, :update, :destroy]
    end
    resources :products do
      resources :discs, only: [:create, :update]
      resources :songs, only: [:create, :update]
    end
    resources :labels, only: [:new, :create, :update]
    resources :genres, only: [:new, :create, :update]
    resources :artists, only: [:new, :create, :update]
    resources :arrivals, only: [:index, :show, :new, :create]
  end
  get 'administrators/top' => 'administrators#top', as: "administrators_top"
  # resources :administrators
  # get 'administrators' => 'administrators#top', as: 'administrators'
  # get 'administrators/users/:id' => 'administrators#show', as: 'administrators_user_main'
  # get 'administrators/users/:id/edit' => 'administrators#edit', as: 'edit_administrators_user_main'
  # patch 'administrators/users/:id' => 'administrators#update', as: 'update_administrators_user_main'
  # put 'administrators/users/:id' => 'administrators#update'
  # get 'administrators/show'
  # get 'administrators/edit'
  root 'products#index'

  devise_for :administrators, controllers: {
    sessions:      'administrators/sessions',
    passwords:     'administrators/passwords',
    registrations: 'administrators/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  get 'thanks/index' => 'thanks#index', as: "thanks"

  resources :users, only: [:index, :edit, :update, :show, :destroy, :create] do
    resources :addresses, only: [:index, :new, :create, :edit, :update, :destroy, :show]
  end

resources :products do
      resources :discs, only: [:create, :update]
      resources :songs, only: [:create, :update]
    end

  resources :receipts, only: [:new, :create, :update]




  get "search" => "products#search"

  resources :cart_items, only: [:create, :update]


#開発の便宜上、一旦ネストを外す　ここから


  resources :arrivals, only: [:index, :show, :new, :create]



#開発の便宜上、一旦ネストを外す　ここまで
  resources :labels, only: [:new, :create, :update]
  resources :genres, only: [:new, :create, :update]
  resources :artists, only: [:new, :create, :update]



  resources :carts, only: [:index, :create, :destroy]
  put "cart_update" => "carts#update"
  # 引数を指定せずにupdateアクションを呼び出すため、別でルーティングを設定

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



   # def day_total_price
   #   receipts  = Receipt.where(created_at: search_date.in_time_zone.all_day)
   #   total_price = 0
   #   receipts.each do |receipt|
   #     total_price += receipt.total_price
   #   end
   # end
   # array = []
   # ReceiptItem.all.each do |product|
   #   array << receipt_item.price
   # end
   # array.sum
   #
end

app/controllers/Administrators/administrators_controller.rb
class AdministratorsController < ApplicationController
  def index
  end

  def show
  end

  def top
  end
end

app/controllers/administrators/addresses_controller.rb
class Administrators::AddressesController < ApplicationController
  before_action :authenticate_administrator!

  def index
    @user = User.find(params[:user_id])
    @addresses = Address.all
    render "addresses/index"
  end


  def edit
    @user = User.find(params[:user_id])
    @address = Address.find(params[:id])
    render "addresses/edit"
  end

  def update
    @user = User.find(params[:user_id])

    if  @user.update(address_params)
      flash[:notice] = "successfully "
      redirect_to administrators_user_addresses_path(@user.id)
    else
      flash[:notice] = "error "
      render 'addresses/edit'
    end
  end


  def destroy
    user = User.find(params[:user_id])
    address =Address.find(params[:id])
    address.destroy
    redirect_to administrators_user_addresses_path(user.id)
  end

  private

  def address_params
    params.require(:address).permit(:id, :family_name,:first_name,:family_name_kana, :first_name_kana, :post, :a_address, :phone, :user_id, :pulldown_name)
  end
end

app/controllers/administrators/arrivals_controller.rb
class Administrators::ArrivalsController < ApplicationController
  before_action :authenticate_administrator!

  def index
    @arrivals = Arrival.where.not(arrival_amount: 0).page(params[:page]).per(20).order(created_at: :desc)
    render 'arrivals/index'
  end
  def show
    @product = Product.find(params[:id])
    @arrivals = @product.arrivals.where.not(arrival_amount: 0).page(params[:page]).per(20).order(created_at: :desc)
    render 'arrivals/index'
  end

  def new
  end

  def create
  end
end

app/controllers/administrators/confirmations_controller.rb
# frozen_string_literal: true

class Administrators::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/administrators/discs_controller.rb
Administrators::class DiscsController < ApplicationController
  def create
  end

  def update
  end
end

app/controllers/administrators/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Administrators::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/administrators/passwords_controller.rb
# frozen_string_literal: true

class Administrators::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/administrators/products_controller.rb
class Administrators::ProductsController < ApplicationController
  before_action :authenticate_administrator!

  def index
    @products = Product.all
    @products = Product.page(params[:page]).per(16)
    render 'products/index'
  end
  def show
    @product = Product.find(params[:id])
    @discs = @product.discs.all
    render 'products/show'
  end
  def new
    @product = Product.new
    @product.arrivals.build #子のarrivalsも同時に保存
    @disc = @product.discs.build #cocoon 子のdiscsも同時に保存
    @song = @disc.songs.build #cocoon 孫のsongsも同時に保存
    render "administrators/products/new"
  end
  def create
    @product = Product.new(product_params)
    #ここに“if current管理者“の記述が入る
    @product.stock_amount = params[:product][:arrivals_attributes][:"0"][:arrival_amount]

    if @product.save
      redirect_to administrators_products_path
    else
      render 'administrators/products/new'
    end
  end
  def edit
    @product = Product.find(params[:id])
    @new_arrival = Arrival.new
    render "administrators/products/edit"
  end
  def update
    #ここに“if current管理者“の記述が入る
    @product = Product.find(params[:id])
    @new_arrival = Arrival.new(product_id: params[:id], arrival_amount: params[:arrival][:arrival_amount])
    if @product.update(product_params)
      @new_arrival.save
      new_stock = @product.stock_amount + @new_arrival.arrival_amount
      @product.update!(stock_amount: new_stock)
      # flash[:success] = “更新しました”
      redirect_to administrators_product_path(@product.id)
    else
      render 'administrators/products/edit'
    end
  end
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end
  def search
    @products = Product.search(params[:search]) #params[:search]の値はモデルのSearch.rbを参照する
  end
  private
  def product_params
    #（下2行は、cocoonの記述。）
    #上の行から順番に躓いた点
    #.permit内には、artist_id等も忘れずに書く。←permit内には送信したい値のカラムを全部書く！
    #
    #discs_attrubutes:[:id(cocoon必須), :カラム名, :カラム名, :done. :_destroy(=アソシエーションしてるproductが消えた時に(モデルで定義済 allow_destroy)、discsも消去]
    #songs_attributes:[:id(cocoon必須), :カラム名, :カラム名,:_destroy(=アソシエーションしてるdiscsが消えた時に(モデルで定義済 allow_destroy)、songsも消去)]
    params.require(:product).permit(:product_name, :product_image, :status, :price, :stock_amount, :artist_id, :genre_id, :label_id,
        arrivals_attributes:[:id, :product_id, :arrival_amount, :_destroy ],
        discs_attributes: [:id, :disc_num, :disc_name, :done, :_destroy,
          songs_attributes: [:id, :song_num, :song_name, :_destroy]])
  end
end

app/controllers/administrators/registrations_controller.rb
# frozen_string_literal: true

class Administrators::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/administrators/sessions_controller.rb
# frozen_string_literal: true

class Administrators::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end
  def after_sign_out_path_for(resource)
      new_administrator_session_path
  end
  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/administrators/unlocks_controller.rb
# frozen_string_literal: true

class Administrators::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/administrators/users_controller.rb
class Administrators::UsersController < ApplicationController
	before_action :authenticate_administrator!

	def index
		@users = User.search(params[:search]).page(params[:page])
		render "administrators/index"
	end

	def edit
		@user =User.find(params[:id])
		#find =PK
		@address =Address.find_by(user_id: @user.id)
		#find_by =カラム
		render "administrators/edit"
	end

	def show
		@user =User.find(params[:id])
		#find =PK
		@address =Address.find_by(user_id: @user.id)

		@receipts = Receipt.page(params[:page]).per(5)
		#find_by =カラム
		#@address =Address.find(@user.id)
		#@address =User.find(@user.address_id)
		render "administrators/show"
	end

	def destroy
		user = User.find(params[:id])
		user.destroy
		redirect_to users_path
	end

	def update
		@user = User.find(params[:id])
		if	@user.update(user_params)
			flash[:notice] = "successfully "
			redirect_to administrators_user_addresses_path(@user.id)
		else
			flash[:notice] = "error "
			render 'administrators/edit'
		end
	end

	private

	def user_params
		params.require(:user).permit(:email,:family_name,:first_name,:family_name_kana, :first_name_kana, addresses_attributes:[:id, :post, :a_address, :phone, :_destroy, :pulldown_nama])
	end
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :authenticate_administrator!
  def index
    @users = User.search(params[:search]).page(params[:page]).per(30)
  end

  def show
    @user      = User.find(params[:id])
    @address = Address.find_by(user_id: @user.id)
    @receipts = Receipt.order(created_at: :desc).page(params[:page]).per(5)

    render "users/show"
  end

  def edit
    @user      = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to administrators_user_path(@user.id)
  end

  def top
    @receipts = Receipt.order(created_at: :desc).page(params[:page]).per(10)
    search_date = DateTime.now
    @dayreceipts           = Receipt.where(created_at: search_date.in_time_zone.all_day)
    @monthreceipts       = Receipt.where(created_at: search_date.in_time_zone.all_month)
    @yearreceipts          = Receipt.where(created_at: search_date.in_time_zone.all_year)
    @day_total_price     = @dayreceipts.sum(:total_price)
    @month_total_price = @monthreceipts.sum(:total_price)
    @year_total_price    = @yearreceipts.sum(:total_price)
    @total_price             = @receipts.sum(:total_price)

  end


  private
  def user_params
    params.require(:user).permit(:family_name,
                                       :first_name,
                                       :family_name_kana,
                                       :first_name_kana,
                                       :email,
                                        addresses_attributes: [:id, :post,
                                                                   :a_address,
                                                                   :phone,
                                                                   :pulldown_name])
  end

  def receipt_params
    params.require(:receipt).permit(:status)
  end


end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="edit-user-info">
        <% if @user.errors.any? %>
            <ul>
                <% @user.errors.full_messages.each do |message| %>
                    <li>
                        <%= message %>
                    </li>
        		    <% end %>
            </ul>
        <% end %>
        <h1>ユーザ情報編集</h1>
          <%= form_for(@user, url: administrators_user_path(@user.id)) do |f| %>
            <div class="box1">
              <div class="name1">
                <h4>姓（漢字）</h4>
                <%= f.text_field :family_name,:class=>"form" %>
              </div>
              <div class="name1">
                <h4>名（漢字）※全角入力</h4>
                <%= f.text_field :first_name,:class=>"form" %>
              </div>
              <div class="name1">
                <h4>姓（カナ）</h4>
                <%= f.text_field :family_name_kana,:class=>"form" %>
              </div>
              <div class="name1">
                <h4>名（カナ）※全角入力</h4>
                <%= f.text_field :first_name_kana,:class=>"form" %>
              </div>

              <%= f.fields_for :addresses, @user.addresses.first do |i| %>
          　　　　<h4>住所の名前</h4>
                <%= i.text_field :pulldown_name %>
                <h4>郵便番号※半角入力、ハイフン不要</h4>
                <%= i.text_field :post %>
                <h4>住所</h4>
                <%= i.text_field :a_address %>
                <h4>電話番号※半角入力、ハイフン不要</h4>
                <%= i.text_field :phone %>
              <% end %>
              <h4>メールアドレス</h4>
              <%= f.text_field :email %>
              <p class="text-center">
                <%= f.submit '保存', class: 'update' %>
              </p>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>


app/views/administrators/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="user-lists">
      <%= form_tag(administrators_users_path, method: :get) do %>
        <p>
        <%= text_field_tag :search %>
        <%= submit_tag "🔍", name: :nil %>
        </p>
        <% end %>
        <h1>ユーザ一覧</h1>

        <p class="array">新着順▼</p>
        <div class="user-info">
          <% @users.each do |user| %>
            <div class="user-list">
              <div class="user-list-left">
                <%= user.family_name %>
                <%= user.first_name %>
              </div>
              <div class="user-list-right">
                <button><%= link_to "詳細", administrators_user_path(user.id) %></button>
              </div>
            </div>
          <% end %>
        </div>
      </div>
        <%= paginate @users %>
    </div>
  </div>
</div>

app/views/administrators/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
        <h2>ユーザ詳細</h2>
          <div class="box1">
            <h5>姓（漢字）</h5>
            <%= @user.family_name %>
            <h5>名（漢字）</h5>
            <%= @user.first_name %>
            <h5>姓（カナ）</h5>
            <%= @user.family_name_kana %>
            <h5>姓（カナ）</h5>
            <%= @user.first_name_kana %>
                <h5>郵便番号※半角入力、ハイフン不要</h5>
                <%= @address.post %>
                <h5>住所</h5>
                <%= @address.a_address %>
                <h5>電話番号※半角入力、ハイフン不要</h5>
                <%= @address.phone %>
            <h5>メールアドレス</h5>
            <%= @user.email %>
          </div>
            <button type="button" class="btn btn-success">
              <%= link_to 'ユーザ情報を編集', edit_administrators_user_path(@user.id) %>
            </button>
            <button type="button" class="btn btn-warning">
              <%= link_to administrators_user_addresses_path(@user.id) do %>お届け先の住所の登録・変更・削除はこちら
              <% end %>
            </button>
            <button type="button" class="btn btn-danger">
              <%= link_to '退会', user_path(@user), method: :delete, data: { confirm: '退会しますか？' }%>
            </button>
             <h4>購入履歴一覧</h4>
             <p>新着順▼</p>
              <% @receipts.each do |receipt| %>
                    <p>注文日：<%= receipt.created_at.strftime("%Y-%m-%d") %></p>
                    <p>注文者：<%= receipt.purchaser_family_name%><%= receipt.purchaser_first_name %></p>
                    <p>
                      配送ステータス：
                      <%= receipt.status %>
                    </p>
                    <div class="box1">
                        <% receipt.receipt_items.each do |item| %>
                            <%= attachment_image_tag item, :product_image_id, format: 'jpeg', fallback: 'no_image.jpg', size: '40x40' %>
                            <%= item.product_name %>
                            <%= (item.price*1.1).floor %>円（税込み）
                            数量：　<%= item.product_amount %>枚
                        <% end %>
                        <p>送付先</p>
                        <%= receipt.delivery_address %>
                        <p>決済方法</p>
                        <%= receipt.settlement %>
                        <p>小計：　<%= receipt.total_price_without_tax %>円</p>
                        <p>消費税：<%= receipt.tax_price.floor%>円</p>
                        <p>送料：  500円</p>
                        <p>購入価格総計：<%= receipt.total_price.floor %></p>
                    </div>
              <% end %>
                <%= paginate @receipts %>
    </div>
  </div>
</div>

app/views/administrators/top.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <h1 class="text-center">管理者ページ</h1>
          <h2 class="title">売上確認</h2><br>
          <div class="box1">
              <p>日別売上：<%= @day_total_price %>円</p><br>
              <p>月別売上：<%= @month_total_price %>円</p><br>
              <p>年別売上：<%= @year_total_price %>円</p><br>
              <p>総売上：<%= @total_price %>円</p>
          </div>


          <h2 class="title">購入履歴一覧</h2>
          <p class="array">新着順▼</p>
          <div class="box1 purchase-history-lists">
                  <% @receipts.each do |receipt| %>
                    <p>注文日：<%= receipt.created_at.strftime("%Y-%m-%d") %></p>
                    <p>注文者：<%= receipt.purchaser_family_name%><%= receipt.purchaser_first_name %></p>
                    <p>
                      配送ステータス：
                      <%= form_for receipt, url: receipt_path(receipt.id) do |f| %>
                        <%= f.select :status, [["受付", "0"], ["準備中", "1"], ["配送済み", "2"]], :selected =>receipt.status_before_type_cast %>
                        <%= f.submit "保存" %>
                      <% end %>
                    </p>
                    <% receipt.receipt_items.each do |item| %>
                      <%= attachment_image_tag item, :product_image_id, format: 'jpeg', fallback: 'no_image.jpg', size: '40x40' %>
                      <%= item.product_name %>
                      <p>数量：<%= item.product_amount %>枚</p>
                      <p>価格：<%= item.price %></p>
                    <% end %>
                    <p>送付先</p>
                    <%= receipt.delivery_address %>
                    <p>決済方法</p>
                    <%= receipt.settlement %>
                    <p>小計：　<%= receipt.total_price_without_tax %>円</p>
                    <p>消費税：<%= receipt.tax_price.floor%>円</p>
                    <p>送料：  500円</p>
                    <p>購入価格総計：<%= receipt.total_price_with_tax.floor %>円</p>
                    <hr>
                  <% end %>
          </div>

          <%= paginate(@receipts) %>
        </div>
    </div>
</div>