config/routes.rb
Rails.application.routes.draw do
  namespace :administrators do
    resources :users, only: [:index, :edit, :update, :show, :destroy, :create] do
      resources :addresses, only: [:index, :new, :create, :edit, :update, :destroy]
    end
    resources :products do
      resources :discs, only: [:create, :update]
      resources :songs, only: [:create, :update]
    end
    resources :labels, only: [:new, :create, :update]
    resources :genres, only: [:new, :create, :update]
    resources :artists, only: [:new, :create, :update]
    resources :arrivals, only: [:index, :show, :new, :create]
  end
  get 'administrators/top' => 'administrators#top', as: "administrators_top"
  # resources :administrators
  # get 'administrators' => 'administrators#top', as: 'administrators'
  # get 'administrators/users/:id' => 'administrators#show', as: 'administrators_user_main'
  # get 'administrators/users/:id/edit' => 'administrators#edit', as: 'edit_administrators_user_main'
  # patch 'administrators/users/:id' => 'administrators#update', as: 'update_administrators_user_main'
  # put 'administrators/users/:id' => 'administrators#update'
  # get 'administrators/show'
  # get 'administrators/edit'
  root 'products#index'

  devise_for :administrators, controllers: {
    sessions:      'administrators/sessions',
    passwords:     'administrators/passwords',
    registrations: 'administrators/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  get 'thanks/index' => 'thanks#index', as: "thanks"

  resources :users, only: [:index, :edit, :update, :show, :destroy, :create] do
    resources :addresses, only: [:index, :new, :create, :edit, :update, :destroy, :show]
  end

resources :products do
      resources :discs, only: [:create, :update]
      resources :songs, only: [:create, :update]
    end

  resources :receipts, only: [:new, :create, :update]




  get "search" => "products#search"

  resources :cart_items, only: [:create, :update]


#開発の便宜上、一旦ネストを外す　ここから


  resources :arrivals, only: [:index, :show, :new, :create]



#開発の便宜上、一旦ネストを外す　ここまで
  resources :labels, only: [:new, :create, :update]
  resources :genres, only: [:new, :create, :update]
  resources :artists, only: [:new, :create, :update]



  resources :carts, only: [:index, :create, :destroy]
  put "cart_update" => "carts#update"
  # 引数を指定せずにupdateアクションを呼び出すため、別でルーティングを設定

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :artist
	belongs_to :genre
	belongs_to :label

	has_many :discs, dependent: :destroy
	accepts_nested_attributes_for :discs, reject_if: :all_blank, allow_destroy: true  #cocoon。discsも同時にデータ作成(保存)
	                                                             # ↑ productが消えたら、discsも消える(product_paramsに関係有)
	has_many :arrivals, dependent: :destroy
	accepts_nested_attributes_for :arrivals, reject_if: :all_blank, allow_destroy: true

	has_many :cart_items, dependent: :destroy
	has_many :carts, through: :cart_items

    attachment :product_image #refile用の記述

	enum status: { 販売中: 0, 販売停止中: 1 } #statusはproductテーブルにあるカラム。

	default_scope -> { order(created_at: :desc) }
	#:descでidの降順（新着順）となる

	def self.search(search)#productコントローラのparams[:search]と繋がっている。
		if search
			Product.where(['product_name LIKE ?', "%#{search}%"])#whereで検索した %#{search}% の値を上の(search)に返す→コントローラにいく。
	        # %#{search}% は、Productモデル(データベース)のプロパティ(SQL,あいまい検索)
		else
			Product.all #検索ワードがないときは全データ表示
	    end

	end
	[:product_name, :artist_id, :genre_id, :label_id, :status, :price, :stock_amount].each do |v|
		validates v, presence: true
	end
end

app/controllers/administrators/products_controller.rb
class Administrators::ProductsController < ApplicationController
  before_action :authenticate_administrator!

  def index
    @products = Product.all
    @products = Product.page(params[:page]).per(16)
    render 'products/index'
  end
  def show
    @product = Product.find(params[:id])
    @discs = @product.discs.all
    render 'products/show'
  end
  def new
    @product = Product.new
    @product.arrivals.build #子のarrivalsも同時に保存
    @disc = @product.discs.build #cocoon 子のdiscsも同時に保存
    @song = @disc.songs.build #cocoon 孫のsongsも同時に保存
    render "administrators/products/new"
  end
  def create
    @product = Product.new(product_params)
    #ここに“if current管理者“の記述が入る
    @product.stock_amount = params[:product][:arrivals_attributes][:"0"][:arrival_amount]

    if @product.save
      redirect_to administrators_products_path
    else
      render 'administrators/products/new'
    end
  end
  def edit
    @product = Product.find(params[:id])
    @new_arrival = Arrival.new
    render "administrators/products/edit"
  end
  def update
    #ここに“if current管理者“の記述が入る
    @product = Product.find(params[:id])
    @new_arrival = Arrival.new(product_id: params[:id], arrival_amount: params[:arrival][:arrival_amount])
    if @product.update(product_params)
      @new_arrival.save
      new_stock = @product.stock_amount + @new_arrival.arrival_amount
      @product.update!(stock_amount: new_stock)
      # flash[:success] = “更新しました”
      redirect_to administrators_product_path(@product.id)
    else
      render 'administrators/products/edit'
    end
  end
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end
  def search
    @products = Product.search(params[:search]) #params[:search]の値はモデルのSearch.rbを参照する
  end
  private
  def product_params
    #（下2行は、cocoonの記述。）
    #上の行から順番に躓いた点
    #.permit内には、artist_id等も忘れずに書く。←permit内には送信したい値のカラムを全部書く！
    #
    #discs_attrubutes:[:id(cocoon必須), :カラム名, :カラム名, :done. :_destroy(=アソシエーションしてるproductが消えた時に(モデルで定義済 allow_destroy)、discsも消去]
    #songs_attributes:[:id(cocoon必須), :カラム名, :カラム名,:_destroy(=アソシエーションしてるdiscsが消えた時に(モデルで定義済 allow_destroy)、songsも消去)]
    params.require(:product).permit(:product_name, :product_image, :status, :price, :stock_amount, :artist_id, :genre_id, :label_id,
        arrivals_attributes:[:id, :product_id, :arrival_amount, :_destroy ],
        discs_attributes: [:id, :disc_num, :disc_name, :done, :_destroy,
          songs_attributes: [:id, :song_num, :song_name, :_destroy]])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

def index
  #.per(12)は、kaminariで12件表示
  @products = Product.page(params[:page]).per(16)
end

def show
 @product = Product.find(params[:id])
 @discs = @product.discs.all
 @user = current_user
 @cart_item = @product.cart_items.build

end

def new
 @product = Product.new
   @product.arrivals.build #子のarrivalsも同時に保存
   @disc = @product.discs.build #cocoon 子のdiscsも同時に保存
   @song = @disc.songs.build #cocoon 孫のsongsも同時に保存
 end

 def create
   product = Product.new(product_params)
   product.stock_amount = params[:product][:arrivals_attributes][:"0"][:arrival_amount]
   #ここに“if current管理者“の記述が入る
   product.save!
   redirect_to products_path
 end

 def edit
   @product = Product.find(params[:id])
 end

 def update
   #ここに“if current管理者“の記述が入る
   @product = Product.find(params[:id])
   if @product.update(product_params)
     # flash[:success] = “更新しました”
     redirect_to edit_product_path(@product)
   else
     render ‘edit’
   end
 end

 def destroy
   @product = Product.find(params[:id])
   @product.destroy
   redirect_to products_path
 end

 def search
   @products = Product.search(params[:search]) #params[:search]の値はモデルのSearch.rbを参照する
 end

 private
 def product_params
   #（下2行は、cocoonの記述。）
   #上の行から順番に躓いた点
   #.permit内には、artist_id等も忘れずに書く。←permit内には送信したい値のカラムを全部書く！
   #
   #discs_attrubutes:[:id(cocoon必須), :カラム名, :カラム名, :done. :_destroy(=アソシエーションしてるproductが消えた時に(モデルで定義済 allow_destroy)、discsも消去]
   #songs_attributes:[:id(cocoon必須), :カラム名, :カラム名,:_destroy(=アソシエーションしてるdiscsが消えた時に(モデルで定義済 allow_destroy)、songsも消去)]
   params.require(:product).permit(:product_name, :product_image, :status, :price, :stock_amount, :artist_id, :genre_id, :label_id,
     arrivals_attributes:[:id, :product_id, :arrival_amount, :_destroy ],
     discs_attributes: [:id, :disc_num, :disc_name, :done, :_destroy,
       songs_attributes: [:id, :song_num, :song_name, :_destroy]])
 end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_arrival_fields.html.erb
<div class="nested-fields form-inline">
  <div class="form-group">
  	<p>ディスク名</p>
	   <%= f.number_field :arrival_amount %>
  </div>
</div>

app/views/products/_disc_fields.html.erb
<div class="nested-fields form-inline">
  <div class="form-group">
  	<p>ディスク名</p>
	<%= f.number_field :disc_num,:class=>"num-form" %>
	<%= f.text_field :disc_name %>
	<%= link_to_remove_association "ディスクを削除", f %>
  </div>
	  <p class="song-name">曲名</p>
	<%= f.fields_for :songs do |song| %>
		<%= render 'products/song_fields', f: song %><!-- cocoonの仕様の表記。renderで、_disc_fields.html.erb を呼び出す -->
		<!-- ↑ f: song の f はproductのform_forで定義した変数。 -->
	<% end %>
			<%= link_to_add_association "曲を追加", f, :songs, :class=>"add-butoon" %> <!-- 追加ボタンは階層が一つ上のviewファイル内に書く -->

</div>

app/views/products/_song_fields.html.erb
<div class="nested-fields form-inline">
  <div class="form-group">
		<%= f.number_field :song_num,:class=>"num-form" %>
		<%= f.text_field :song_name %>
		<%= link_to_remove_association "曲を削除", f, :class=>"add-button" %>
  </div>
</div>

app/views/products/index.html.erb
<script src="https://unpkg.com/infinite-scroll@3/dist/infinite-scroll.pkgd.js"></script>
    <script>
    $(function(){
      $(document).on("scroll",function(){
      var elem = document.querySelector('#infinite-scroll');
        $('#infinite-scroll').infiniteScroll({
          path: "nav.pagination a[rel=next]",
          append: ".products",
          // scrollThreshold: 500,
          history: false,
          prefill: false,
          status: '.page-load-status'
          });
        });
      });
</script>



<h2>商品一覧</h2>



<% if administrator_signed_in? %>

  <div id="infinite-scroll">
    <div class="products">

      <div class="clearfix">

        <% @products.each do |product| %>
          <div class="contents-item">
            <!-- 商品画像 -->
            <%= attachment_image_tag product, :product_image, fallback: "no_image.jpg", size: "100x100" %>
            <!-- 商品名 -->
            <p><%= link_to administrators_product_path(product.id) do %><%= product.product_name %><% end %></p>
            <!-- 商品価格 -->
            <%= (product.price*1.1).floor %>円（税込み）
            <%# .floorは小数点以下切り捨て %>

            <% if product.status == "販売停止中" %>
              <p><%= product.status %></p>
            <% end %>
            <!-- 在庫の有無　一旦コメントアウト -->
            <% if product.stock_amount == 0 %>
              <p> -- SOLD OUT -- </p>
            <% end %>

          </div>
        <% end %>
      </div>
      <%= paginate @products %>
    </div>
  </div>

<% else %>

  <div id="infinite-scroll">
    <div class="products">

      <div class="clearfix">

        <% @products.each do |product| %>
          <div class="contents-item">
            <!-- 商品画像 -->
            <div><%= attachment_image_tag product, :product_image, fallback: "no_image.jpg", size: "100x100" %></div>
            <!-- 商品名 -->
            <div><%= link_to product_path(product.id) do %><%= product.product_name %><% end %></div>
            <!-- 商品価格 -->
            <div><%= (product.price*1.1).floor %>円（税込み）</div>
            <%# .floorは小数点以下切り捨て %>


            <% if product.status == "販売停止中" %>
              <p><%= product.status %></p>
            <% end %>
            <!-- 在庫の有無　一旦コメントアウト -->
            <% if product.stock_amount == 0 %>
              <p> -- SOLD OUT -- </p>
            <% end %>
          </div>
        <% end %>
      </div>
      <%= paginate @products %>
    </div>
  </div>

<% end %>

app/views/products/search.html.erb
<h2>検索結果</h2>

<ul>
   <% @products.each do |product| %>
	<li>
	  <%= attachment_image_tag product, :product_image, fallback: "no_image.jpg", size: "100x100" %>
	  <%= link_to product.product_name, product_path(product.id) %>
	  <%= (product.price*1.1).floor %>円（税込み）
	  <%= product.status %>
	</li>
   <% end %>
</ul>

app/views/products/show.html.erb
<div class="product-info clearfix">
  <h2>商品詳細</h2>
  <div class="product-image"><%= attachment_image_tag @product, :product_image, format: 'jpeg', fallback: 'no_image.jpg', size: '300x300' %></div>
  <div class="product-detail">
    <div class="detail-left">
      <h3>曲リスト</h3>
      <% @discs.each do |disc| %>
        <p class="disc-name">ディスク <%= disc.disc_name %></p>
        <ul class="song">
          <% disc.songs.each do |song| %>
            <li class="song-list"><%= song.song_num %>.<%= song.song_name %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <div class="detail-right">
      <h3 class="product_name"><%= @product.product_name %></h3>
      <p class="product-detail-item"><%= @product.artist.artist_name %></p>
      <p class="product-detail-item"><%= @product.label.label_name %></p>
      <p class="product-detail-item"><%= (@product.price*1.1).floor %>円（税込み）</p>
      <p class="product-detail-item">在庫：　<%= @product.stock_amount %>枚</p>
      <% if @product.status == "販売停止中" %>
        <p class="product-detail-item"><%= @product.status %></p>
      <% end %>
      <p class="product-detail-item"><%= @product.genre.genre_name %></p>


      <% if administrator_signed_in? %>
        <div class="product-change">
          <div>
            <%= link_to "編　集", edit_administrators_product_path(@product.id) ,:class=>"change-button"%>
          </div>
          <div>
            <%= link_to "削　除", product_path(@product), method: :delete, data:{ confirm: '本当に消しますか？' },:class=>"change-button" %>
          </div>
        </div>
        <p><%= link_to "この商品の入荷履歴を見る", administrators_arrival_path(@product.id) %></p>
      <% else %>

        <% if @product.stock_amount != 0 && @product.status != "販売停止中" %>

          <%= form_for(@cart_item, url:carts_path) do |f| %>
            <!-- url:carts_pathで、cartコントローラーのcreateアクションに入力情報を送る -->
            <%= f.hidden_field :product_id, value: @product.id %>
            <!-- .hidden_fieldのフォームはviewには表示されない。@productが持つidをcarts_pathでcartコントローラーへ渡している。 -->
            <p><%= f.select :product_amount, 1..@product.stock_amount %>  枚</p>
            <p><%= f.submit "カートに入れる" ,:class=>"button" %></p>
          <% end %>
        <% end %>
      <% end %>
      <p><%= link_to "商品一覧に戻る", products_path %></p>
    </div>
  </div>

</div>