config/routes.rb
Rails.application.routes.draw do
  namespace :administrators do
    resources :users, only: [:index, :edit, :update, :show, :destroy, :create] do
      resources :addresses, only: [:index, :new, :create, :edit, :update, :destroy]
    end
    resources :products do
      resources :discs, only: [:create, :update]
      resources :songs, only: [:create, :update]
    end
    resources :labels, only: [:new, :create, :update]
    resources :genres, only: [:new, :create, :update]
    resources :artists, only: [:new, :create, :update]
    resources :arrivals, only: [:index, :show, :new, :create]
  end
  get 'administrators/top' => 'administrators#top', as: "administrators_top"
  # resources :administrators
  # get 'administrators' => 'administrators#top', as: 'administrators'
  # get 'administrators/users/:id' => 'administrators#show', as: 'administrators_user_main'
  # get 'administrators/users/:id/edit' => 'administrators#edit', as: 'edit_administrators_user_main'
  # patch 'administrators/users/:id' => 'administrators#update', as: 'update_administrators_user_main'
  # put 'administrators/users/:id' => 'administrators#update'
  # get 'administrators/show'
  # get 'administrators/edit'
  root 'products#index'

  devise_for :administrators, controllers: {
    sessions:      'administrators/sessions',
    passwords:     'administrators/passwords',
    registrations: 'administrators/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  get 'thanks/index' => 'thanks#index', as: "thanks"

  resources :users, only: [:index, :edit, :update, :show, :destroy, :create] do
    resources :addresses, only: [:index, :new, :create, :edit, :update, :destroy, :show]
  end

resources :products do
      resources :discs, only: [:create, :update]
      resources :songs, only: [:create, :update]
    end

  resources :receipts, only: [:new, :create, :update]




  get "search" => "products#search"

  resources :cart_items, only: [:create, :update]


#開発の便宜上、一旦ネストを外す　ここから


  resources :arrivals, only: [:index, :show, :new, :create]



#開発の便宜上、一旦ネストを外す　ここまで
  resources :labels, only: [:new, :create, :update]
  resources :genres, only: [:new, :create, :update]
  resources :artists, only: [:new, :create, :update]



  resources :carts, only: [:index, :create, :destroy]
  put "cart_update" => "carts#update"
  # 引数を指定せずにupdateアクションを呼び出すため、別でルーティングを設定

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/receipt.rb
class Receipt < ApplicationRecord
	has_many :receipt_items
	belongs_to :user


	enum settlement:{銀行振込: 0, クレジットカード払い: 1, 代引き払い: 2}
	enum status:{受付: 0, 準備中: 1, 配送済み: 2}

	def total_price_without_tax
		sum = 0
		self.receipt_items.each do |item|
			sum += item.price*item.product_amount
		end
		return sum
	end

	def tax_price
		sum = 0
		self.receipt_items.each do |item|
			sum += item.price*item.product_amount
		end
		sum*0.1
	end

	def total_price_with_tax
		sum = 0
		self.receipt_items.each do |item|
			sum += item.price
		end
		return sum*1.1+500
	end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController

 def index
 end


 def new
   @user = current_user
   @receipt = Receipt.new
   @addresses = @user.addresses.all

   # @cart = @user.cart
   @cart_items = @user.cart.products.all
   sum= 0
   @cart_items.each do |item|
     item_amount = item.cart_items.first.product_amount
     sum += item.price*item_amount
   end
   @total = (sum*1.1)+500
   @tax = sum*0.1

 end


 def create
   r = Receipt.new(receipt_create_params)
   r.user_id = current_user.id
   r.purchaser_family_name = current_user.family_name
   r.purchaser_first_name = current_user.first_name
   r.postage = 500
   r.status = 0
   r.settlement = params[:receipt][:settlement].to_i
   r.save

   current_user.cart.cart_items.each do |a|
     i = ReceiptItem.new
     i.receipt_id = r.id
     i.product_name = a.product.product_name
     i.product_image_id = a.product.product_image_id
     i.price = a.product.price
     i.product_amount = a.product_amount
     i.save!
     sa = Product.find(a.product_id)
     sa.stock_amount = sa.stock_amount - a.product_amount
     sa.save
   end
   current_user.cart.cart_items.destroy_all
   redirect_to thanks_path
 end

 def show
 end

 def update
   @receipt = Receipt.find(params[:id])
   @receipt.update(receipt_params)
   redirect_to administrators_top_path
 end

 private
 def receipt_params
   p = params.require(:receipt).permit(:status)
   p[:status] = params[:receipt][:status].to_i
   return p
 end

 def receipt_create_params
   params.require(:receipt).permit(:total_price,
                                                  :delivery_address,
                                                  :post)
 end

 def update_params
   params.require(:product).permit(:stock_amount)
 end
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/receipts/new.html.erb
<h2>購入情報確認</h2>
<div class="confirm-purchase">

	<%= form_with(model: @receipt, local: true) do |f| %>
		<div class="purchase-detail">
			<h4>お支払い方法の選択</h4>
			<p><%= f.radio_button :settlement, "0" %>銀行振込</p>
			<p><%= f.radio_button :settlement, "1" %>クレジットカード決済</p>
			<p><%= f.radio_button :settlement, "2" %>代金引換</p>


			<h4 id="addresses" data-addresses=<%= @addresses.to_json%>>お届け先の住所の選択</h4>

			<%= f.collection_select :delivery_address, @addresses, :a_address, :pulldown_name %>
			<p class="post"><%= @addresses.first.post %></p>
			<p class="address"><%= @addresses.first.a_address %></p>
			<p><span class="name"><%= @addresses.first.family_name %></span><span class="first-name"><%= @addresses.first.first_name %></span></p>
			<p class="phone"><%= @addresses.first.phone %></p>

			<%= f.hidden_field :post, :value =>"", class: "post" %>
			<!-- ↑addressのhidden_fieldプルダウンメニューで取得してるので消す可能性有り -->


			<%= link_to "別の住所を追加・変更する場合はこちら", new_user_address_path(current_user.id) %>
			<h4>ご請求額</h4>
			<%= @total.floor %>円（税込み）
			<p>(消費税　<%= @tax.floor %>円)</p>
			<p>(送料　500円)</p>
			<%= f.hidden_field :total_price, value: @total.floor %>

		</div>

		<div class="purchase-item">

			<h3>購入内容の選択</h3>
			<% @cart_items.each do |item| %>
				<li class="purchase-item-list">
					<div class="purchase-item-image">
						<%= attachment_image_tag item, :product_image, format: "jpeg", fallback: "no_image.jpg", size: "80x80" %>
					</div>
					<div class="purchase-item-string">
						<p><%= item.product_name %>
						<%= (item.price*1.1).floor %>円（税込み）</p>
						<p><%= item.cart_items.first.product_amount %>枚
						<%= link_to "削除", cart_path(item.cart_items.first.id), method: :delete, data:{ confirm: '本当に消しますか？' } %></p>
					</div>
				</li>
			<% end %>
		</div>
			<div class="confirm"><%= f.submit "購入確定", :class=>"button" %></div>
	<% end %>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		$("#receipt_delivery_address").change(function() {
			var index = $(this).prop("selectedIndex");
			var addresses = $("#addresses").data("addresses");
			var val = $(this).val();
			$('.address').text(addresses[index]["a_address"]);
			$('.post').text(addresses[index]["post"]);
			$('.address').val(addresses[index]["a_address"]);
			$('.post').val(addresses[index]["post"]);
			$('.name').text(addresses[index]["family_name"]);
			$('.first-name').text(addresses[index]["first_name"]);
			$('.phone').text(addresses[index]["phone"]);

		});
	});
</script>

app/views/receipts/show.html.erb
<h3>決済確認</h3>
<div>
	<h4>お支払い方法</h4>

	<h4>お届け先の住所</h4>

	<h4>ご請求額</h4>

</div>
<div>
	<h4>注文する商品の確認</h4>
</div>

<h3>注文内容にお間違いありませんか？</h3>
<%= link_to "購入確定へ進む", _path %>